# Copyright 2024-2025 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz_generated
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ShyunnY/actbot)
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ShyunnY/actbot
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - goheader
    - gosec
    - importas
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: if-return
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1006
        - -ST1005
    testifylint:
      disable:
        - float-compare
        - go-require
      enable-all: true
    unparam:
      check-exported: false
    importas:
      alias:
        - pkg: "golang.org/x/oauth2/github"
          alias: oauthGh
output:
  show-stats: false
run:
  timeout: 10m
version: "2"
