name: setup-deps
description: Install host system dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.0.1
      with:
        go-version: "1.23"
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
